#!/usr/bin/perl
use strict;
use warnings;

use UI::Dialog;
use Term::ReadKey;
use Term::ANSIScreen qw(cls);

my $FileEditor = "/bin/nano";
my $InitDName = "/etc/init.d/wesnoth-server";
my $WESNOTHDIR = "/root/WesnothStartup";
my $BackupCommand = "/root/WesnothBackup/wesnothbackup.pl";

###################################################
# No changes below here
###################################################

my $MMC_ver = "1.1.0";
my $ServerStatus = "foo";

my $d = new UI::Dialog ( backtitle => "Wesnoth Server Management Console v$MMC_ver", height => 20, width => 65, listheight => 5,
	order => [ 'ascii', 'cdialog', 'xdialog' ]);

my $windowtitle = "Welcome to the Wesnoth Server Management Console!";
my $enjoyedtitle = "We hope you enjoyed using WMC!";
my $introtext =
"This is the Wesnoth Server Management Console, a utility for Wesnoth Server operators to manage their servers from a text GUI rather than the command line.";

$d->msgbox( title => $windowtitle, text => $introtext );

if (($d->state() eq "ESC") || ($d->state() eq "CANCEL"))
{
	exit 0;
}

my $menuselection = "";

sub CheckServerStatus
{
	my $running=`ps ax|grep wesnothd|grep -v grep`;
	if ($running ne "")
	{
		$ServerStatus = "Running";
	}
	else
	{
		$ServerStatus = "Stopped";
	}

}

sub MainMenu
{
	my $WantRespawn="ON";
	CheckServerStatus();
	if (-f "$WESNOTHDIR/nostart")
	{
		$WantRespawn="OFF";
	}

	$menuselection = $d->menu( title => "Main Menu", text => "Server is $ServerStatus and respawn is $WantRespawn - Select one:",
                            list => [ '1', 'Start Server',
                                      '2', 'Stop Server',
                                      '3', 'Server Console',
                                      '4', 'Turn Off Respawn',
                                      '5', 'Turn Respawn On',
#                                      '6', 'Edit server.cfg',
#                                      '7', 'Run a Backup',
                                      'q', 'Quit WMC' ] );
}

while (-1)
{
	MainMenu();
	if (($menuselection eq "CANCEL") || ($menuselection eq "ESC") || ($menuselection eq "") || ($menuselection eq "q") || ($menuselection eq "Q"))
	{
		$d->msgbox( title => $enjoyedtitle, text => "Thanks for using WMC..." );
		exit 0;
	}
	if ($menuselection eq "1")
	{
		system("$InitDName start");
	}
	elsif ($menuselection eq "2")
	{
		if ($d->yesno( text => "Confirm stopping the server", text => "Are you sure you want to shut down the server?" ))
		{
			system("$InitDName stop");
			sleep(5);
		}
	}
	elsif ($menuselection eq "3")
	{
		$d->msgbox( text => "To exit the Wesnoth Server console and return to WMC press CTRL-A CTRL-D" );
		system("screen -r");
	}
	elsif ($menuselection eq "4")
	{
		# Turn off respawn
		system("touch $WESNOTHDIR/nostart");
	}
	elsif ($menuselection eq "5")
	{
		# Turn respawn back on
		if (-f "$WESNOTHDIR/nostart")
		{
			unlink("$WESNOTHDIR/nostart");
		}
	}
	elsif ($menuselection eq "6")
	{
		# Edit server config file
		system("$FileEditor $WESNOTHDIR/bin/config");
	}
	elsif ($menuselection eq "7")
	{
		# Run a backup
		system("$BackupCommand");
	}
}

exit 0;
